version: '3.8'

services:
  # NGINX Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80" # Map port 8080 on the host to port 80 in the container
    volumes:
      - ./root:/application # Application code
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/mime.types:/etc/nginx/mime.types
    networks:
      - app-network
    depends_on:
      - php-fpm # Ensure PHP-FPM is up before NGINX starts

  # PHP-FPM Service
  php-fpm:
    # image: php:8.2-fpm
    container_name: php-fpm
    build:
      dockerfile: Dockerfile    
    working_dir: /application 
    env_file:
      - .env
    volumes:
      - .:/application # Application code
    networks:
      - app-network

networks:
  app-network:
    driver: bridge